In [1]:
import numpy as np
import sympy as sp

In [33]:
mat_dim = int(input("Enter the dimention of the matrix: "))
A = np.array([int(input(f"{i} = ")) for i in range(mat_dim*mat_dim)]).reshape(mat_dim,mat_dim)

print(mat_dim)
print(A)

n = int(input("Please enter power of a matrix = "))

# Convert a matrix to sympy Matrix format for multiplication
A = sp.Matrix(sp.simplify(A))
B = sp.Matrix(sp.simplify(A))


for i in range(n-1):
    A = sp.Matrix(sp.simplify(A*B))

    
A

Enter the dimention of the matrix: 3
0 = 1
1 = 2
2 = 3
3 = 4
4 = 5
5 = 6
6 = 7
7 = 8
8 = 9
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Please enter power of a matrix = 3


Matrix([
[ 468,  576,  684],
[1062, 1305, 1548],
[1656, 2034, 2412]])

# Jacobi And Gaussian

In [100]:
mat_dim = int(input("Enter the dimention of the matrix: "))
a = np.array([int(input(f"{i} = ")) for i in range(mat_dim*mat_dim)]).reshape(mat_dim,mat_dim)

print("Enter the vectors\n")
v = [int(input(f"v[{i}] = ")) for i in range(mat_dim)]
print(v)
print(a)


Enter the dimention of the matrix: 3
0 = 20
1 = 1
2 = -2
3 = 3
4 = 20
5 = -1
6 = 2
7 = -3
8 = 20
Enter the vectors

v[0] = 17
v[1] = -18
v[2] = 25
[17, -18, 25]
[[20  1 -2]
 [ 3 20 -1]
 [ 2 -3 20]]


In [101]:
b = a.copy()
b

array([[20,  1, -2],
       [ 3, 20, -1],
       [ 2, -3, 20]])

In [102]:
for i in range(mat_dim):
    for j in range(mat_dim):
        b[i][j] = a[i][j]*-1
        
b

array([[-20,  -1,   2],
       [ -3, -20,   1],
       [ -2,   3, -20]])

In [105]:
guess = [int(input()) for i in range(mat_dim)]
guess

# for i in range(mat_dim):
    

0
0
0


[0, 0, 0]

In [109]:
l = []
guess1 = guess.copy()
itterations = int(input('Please enter number of iterrations: '))

for i in range(itterations):
    print(f"Iteration {i}")
    for r in range(mat_dim):
        s = 0    
        for c in range(mat_dim):
            if r!=c:
                s = s+b[r][c]*guess[c]
                
        guess1[r] = (v[r]+s)/(b[r][r]*-1) 

#         print(f"Div = {b[r][r]}")
#         print(f"sum = {s}\n")
    
    print(guess1)
    guess = guess1

            

Please enter number of iterrations: 3
Iteration 0
[0.999999993778556, -1.0000000821289652, 0.999999950788666]
Iteration 1
[0.9999999991853148, -1.000000002338364, 0.9999999997307139]
Iteration 2
[1.0000000000899896, -1.0000000000269629, 0.9999999999869565]


# Gaussian

In [108]:
guess = [int(input()) for i in range(mat_dim)]
guess

l = []
itterations = int(input('Please enter number of iterrations: '))

for i in range(itterations):
    print(f"Iteration {i}")
    for r in range(mat_dim):
        s = 0    
        for c in range(mat_dim):
            if r!=c:
                s = s+b[r][c]*guess[c]
                
        guess[r] = (v[r]+s)/(b[r][r]*-1) 

#         print(f"Div = {b[r][r]}")
#         print(f"sum = {s}\n")
    
    print(guess)


0
0
0
Please enter number of iterrations: 4
Iteration 0
[0.85, -1.0275, 1.010875]
Iteration 1
[1.0024625, -0.999825625, 0.99977990625]
Iteration 2
[0.999969271875, -1.00000639546875, 1.0000021134921875]
Iteration 3
[1.0000005311226563, -0.9999999739937891, 0.999999950788666]
