# Q 5

In [4]:
import numpy as np

X = np.array([[1,2],[1,4],[1,5]]).reshape(3,2)
beta = np.array([0,1]).reshape(2,1)
y = np.array([1.2,2.8,5.3]).reshape(3,1)



def gradient_func(beta,grad_beta_loss,n):
    for i in range(n+1):
        updated_beta = np.round(beta - 0.02*grad_beta_loss,4)
        print(f"beta{i} =\n {updated_beta}")
        print("")
        beta = updated_beta
        
        
n = int(input("Enter number of iterations = "))

grad_beta_loss = 2*(X.T@X@beta-X.T@y)

gradient_func(beta,grad_beta_loss,n)

Enter number of iterations = 1000
beta0 =
 [[-0.068]
 [ 0.804]]

beta1 =
 [[-0.136]
 [ 0.608]]

beta2 =
 [[-0.204]
 [ 0.412]]

beta3 =
 [[-0.272]
 [ 0.216]]

beta4 =
 [[-0.34]
 [ 0.02]]

beta5 =
 [[-0.408]
 [-0.176]]

beta6 =
 [[-0.476]
 [-0.372]]

beta7 =
 [[-0.544]
 [-0.568]]

beta8 =
 [[-0.612]
 [-0.764]]

beta9 =
 [[-0.68]
 [-0.96]]

beta10 =
 [[-0.748]
 [-1.156]]

beta11 =
 [[-0.816]
 [-1.352]]

beta12 =
 [[-0.884]
 [-1.548]]

beta13 =
 [[-0.952]
 [-1.744]]

beta14 =
 [[-1.02]
 [-1.94]]

beta15 =
 [[-1.088]
 [-2.136]]

beta16 =
 [[-1.156]
 [-2.332]]

beta17 =
 [[-1.224]
 [-2.528]]

beta18 =
 [[-1.292]
 [-2.724]]

beta19 =
 [[-1.36]
 [-2.92]]

beta20 =
 [[-1.428]
 [-3.116]]

beta21 =
 [[-1.496]
 [-3.312]]

beta22 =
 [[-1.564]
 [-3.508]]

beta23 =
 [[-1.632]
 [-3.704]]

beta24 =
 [[-1.7]
 [-3.9]]

beta25 =
 [[-1.768]
 [-4.096]]

beta26 =
 [[-1.836]
 [-4.292]]

beta27 =
 [[-1.904]
 [-4.488]]

beta28 =
 [[-1.972]
 [-4.684]]

beta29 =
 [[-2.04]
 [-4.88]]

beta30 =
 [[-2.108]
 [-5.076]]

In [64]:
grad_beta_loss

array([[3.4],
       [9.8]])

In [65]:
updated_beta = beta - 0.02*grad_beta_loss
updated_beta

array([[-0.068],
       [ 0.804]])

In [66]:
beta = updated_beta
beta

array([[-0.068],
       [ 0.804]])