In [1]:
import numpy as np

In [18]:
# a = np.array([[1,2],[3,4]])
a = np.array([[[[1,2],[3,4]],[[4,6],[4,5]]]])
print(a)

[[[[1 2]
   [3 4]]

  [[4 6]
   [4 5]]]]


## Inverse the matrix use linalg.inv

In [19]:
inv_a  = np.linalg.inv(a)
print(inv_a)

[[[[-2.    1.  ]
   [ 1.5  -0.5 ]]

  [[-1.25  1.5 ]
   [ 1.   -1.  ]]]]


## Multiply two matrix

In [14]:
# np.allclose shows True when both the matrix are not same

np.allclose(np.dot(a,inv_a),np.eye(2))

True

In [15]:
mul_a = np.dot(a,inv_a)
mul_a

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## np.tril or np.triu

In [32]:
l = [i for i in range(1,10)]

a = np.array(l).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
np.tril(a,0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [34]:
np.triu(a,1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])