In [20]:
import numpy as np
import sympy as sym
from IPython.display import display, Math

In [21]:
a = np.array([[3,1,2]
              ,[4,3,9]
              ,[5,6,8]])


b = np.array([[1,1,8]
              ,[3,7,6]
              ,[2,6,4]])

In [22]:
print(a)
print(f'\n{b}')


a.dot(b)

[[3 1 2]
 [4 3 9]
 [5 6 8]]

[[1 1 8]
 [3 7 6]
 [2 6 4]]


array([[ 10,  22,  38],
       [ 31,  79,  86],
       [ 39,  95, 108]])

In [32]:
display(Math(f"a = {sym.latex(sym.simplify(a))}"))

display(Math(f"b = {sym.latex(sym.simplify(b))}"))

display(Math(f"a X b = {sym.latex(sym.simplify(a.dot(b)))}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [31]:
copy_a = a

display(Math(f"Copy of a  = {sym.latex(sym.simplify(copy_a))}"))

<IPython.core.display.Math object>

In [43]:
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
  
# Initializing the matrix  
example_matrix = []  
print("Please give the entries row-wise:")  
  
# For user input  
for _ in range(Rows):  # This for loop is to arrange rows  
    r = []  
    for __ in range(Columns):  # This for loop is to arrange columns  
        r.append(int(input()))  
    example_matrix.append(r)  
  
# Printing the matrix given by user  
for _ in range(Rows):  
    for __ in range(Columns):  
        print(example_matrix[_][__], end = " ")  
    print()  

Give the number of rows:2
Give the number of columns:3
Please give the entries row-wise:
2
1
3
3
3
3
2 1 3 
3 3 3 


In [46]:
import numpy as np  
  
Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
  
print("Please write the elements of the matrix in a single line and separated by a space: ")  
  
# User will give the entries in a single line  
elements = list(map(int, input().split()))  
  
# Printing the matrix given by the user  
matrixx = np.array(elements).reshape(Rows, Columns)  
print(matrixx)  

Give the number of rows:2
Give the number of columns:3
Please write the elements of the matrix in a single line and separated by a space: 
1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]


In [99]:
# display(Math(sym.latex(sym.simplify(example_matrix))))

display(Math(f"Copy of a  = {sym.latex(sym.simplify(matrixx))}"))
# a = np.array(sym.latex(sym.simplify(matrixx)))
print(sym.latex(sym.simplify(matrixx)))

<IPython.core.display.Math object>

\left[\begin{matrix}1 & 2 & 3\\4 & 5 & 6\end{matrix}\right]


In [71]:
l = [1,2,3,4,5,6,7,8,9]
l2 = [1,2,3,3,5,6]
m = np.array(l).reshape(3,3)

print(m)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
print(m1)


[[1, 4], [9, 16]]


In [11]:
import numpy as np
import sympy as sym # This library is used to calculate and display the matrix
from IPython.display import Math,display


n = int(input("Please enter a integer value for rows and columns = "))

no_of_elements = n*n
print(f"no_of_emelents = {no_of_elements}")
l = []
print(f"\nEnter {no_of_elements} elements row wise")
for i in range(no_of_elements):
    l.append(int(input(f"{i} position element = ")))
    
m1 = np.array(l).reshape(n,n) # Matrix 1
# print(m1)



# m1  = sym.latex(sym.simplify(m1))
copy_m1 = sym.Matrix(sym.simplify(m1)) # copy of m1



display(Math(f"m1 = {sym.latex(sym.Matrix(sym.simplify(m1)))}"))
display(Math(f"copy_m1 = {sym.latex(copy_m1)}"))


mat_mul = int(input("Enter how many times the matrix should multiply = ") )
if mat_mul>1:
    for i in range(mat_mul-1):
        m1 = sym.Matrix(sym.simplify(m1*copy_m1))
    print(f"\nThe Value of A power is {mat_mul}")
        
    display(Math(f"Final Matrix = {sym.latex(sym.simplify(m1))}"))
else:
    print(f"\nThe Value of A power is {mat_mul}")
    display(Math(f"Final out put = {sym.latex(sym.Matrix(sym.simplify(m1)))}"))
    
#     display(m1)


Please enter a integer value for rows and columns = 5
no_of_emelents = 25

Enter 25 elements row wise
0 position element = 1
1 position element = 2
2 position element = 3
3 position element = 4
4 position element = 345
5 position element = 34
6 position element = 3
7 position element = 23
8 position element = 12
9 position element = 34
10 position element = 34
11 position element = 3
12 position element = 2
13 position element = 123
14 position element = 12
15 position element = 2
16 position element = 323
17 position element = 4324
18 position element = 234
19 position element = 23
20 position element = 22
21 position element = 3
22 position element = 12
23 position element = 13
24 position element = 3


<IPython.core.display.Math object>

<IPython.core.display.Math object>

Enter how many times the matrix should multiply = 3

The Value of A power is 3


<IPython.core.display.Math object>

#### 